import{a as p,S,i as P}from"./assets/vendor-65ab9a22.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function d(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(r){if(r.ep)return;r.ep=!0;const t=d(r);fetch(r.href,t)}})();const w="/goit-js-hw-12/assets/error-17a1ca3f.svg",q="https://pixabay.com/api/",A="41647148-76dbe9dab66bab2692c283b6e";p.defaults.baseURL=q;let m;const s={key:A,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:1},O=new S(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:500}),y=document.querySelector(".gallery-form"),f=document.querySelector(".search-input"),g=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");async function E(e){if(e.preventDefault(),!f.value.trim()){i("Please fill in the search field");return}try{g.innerHTML="",a(l,!0),a(u,!1),s.q=f.value.trim(),s.page=1;const o=await h();m=o.totalHits,b(o)}catch(o){console.error(o),i("An error occurred. Please try again later.")}}async function M(){try{a(l,!0),a(u,!1);const e=await h();b(e)}catch(e){console.error(e),i("An error occurred. Please try again later.")}}async function h(){return(await p.get("",{params:s})).data}function b(e){if(!e.total){i("Sorry, there are no images matching your search query. Please, try again!"),a(l,!1);return}const o=e.hits.map(({largeImageURL:d,webformatURL:c,tags:r,likes:t,views:n,comments:L,downloads:v})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${d}">
        <img class="api-img" src="${c}" alt="${r}">
        <div class="img-desc">
        <span><b>Likes:</b> <br/>${t}</span>
        <span><b>Views:</b> <br/>${n}</span>
        <span><b>Comments:</b> <br/>${L}</span>
        <span><b>Downloads:</b> <br/>${v}</span>
        </div>
        </a>
        </li>
        `).join("");g.insertAdjacentHTML("beforeend",o),a(l,!1),$(),C(),O.refresh(),y.reset()}function $(){Math.ceil(m/s.per_page)===s.page?i("We're sorry, but you've reached the end of search results."):(s.page+=1,a(u,!0))}function a(e,o){o?e.classList.remove("hidden"):e.classList.add("hidden")}function C(){if(s.page>1){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}}function i(e){P.show({position:"topRight",iconUrl:w,message:e,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",close:!1,closeOnClick:!0,closeOnEscape:!0})}y.addEventListener("submit",e=>E(e));u.addEventListener("click",M);
//# sourceMappingURL=commonHelpers.js.map
